#!/usr/bin/env python3
"""
Generate version metadata for the documentation site from git.

Inputs:  git tags and commits, ``jocky/__init__.py:__version__``.
Outputs: ``site/src/lib/versions.generated.js`` (consumed by the UI),
         ``site/static/versions.json`` (machine-readable),
         ``site/content/project/releases.md`` (release history page).

Run from the repository root or from ``site/``: the script locates the repo
relative to itself, so `npm run gen` works from either place.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parents[1]
REPO = SITE_DIR.parent


def git(*args: str) -> str:
    try:
        return subprocess.run(
            ["git", *args], cwd=REPO, capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def package_version() -> str:
    text = (REPO / "jocky" / "__init__.py").read_text(encoding="utf-8")
    match = re.search(r'__version__\s*=\s*"([^"]+)"', text)
    return match.group(1) if match else "0.0.0"


def release_history() -> list[dict]:
    """Annotated/lightweight tags, newest first."""
    raw = git("tag", "--sort=-creatordate", "--format=%(refname:short)|%(creatordate:short)|%(subject)|%(objectname:short)")
    releases: list[dict] = []
    for line in raw.splitlines():
        parts = line.split("|")
        if len(parts) < 4:
            continue
        tag, date, subject, commit = parts[0], parts[1], parts[2], parts[3]
        releases.append(
            {
                "version": tag,
                "tag": tag,
                "date": date,
                "subject": subject or tag,
                "commit": commit,
            }
        )
    return releases


def commits_since(tag: str, limit: int = 25) -> list[str]:
    if not tag:
        return []
    raw = git("log", f"{tag}..HEAD", "--pretty=format:%h %s", f"-{limit}")
    return [line for line in raw.splitlines() if line.strip()]


def write_releases_page(releases: list[dict], pending: list[str]) -> None:
    lines = [
        "# Releases",
        "",
        "<!-- generated by site/tools/gen_versions.py — do not edit by hand -->",
        "",
        "Every release is a git tag. The documentation site is published from the",
        "tagged commit, and `jocky --version` reports the same string.",
        "",
    ]
    if releases:
        lines += ["| Version | Date | Commit | Notes |", "|---|---|---|---|"]
        lines += [
            f"| `{r['version']}` | {r['date']} | `{r['commit']}` | {r['subject']} |"
            for r in releases
        ]
        lines.append("")
    else:
        lines += ["_No tags yet — the repository is pre-release._", ""]
    if pending:
        lines += ["## Unreleased", "", "Commits after the latest tag:", ""]
        lines += [f"- `{entry}`" for entry in pending]
        lines.append("")
    lines += [
        "## Cutting a release",
        "",
        "```bash",
        "# 1. bump the version in jocky/__init__.py and CHANGELOG.md",
        "# 2. run the suite and regenerate the evidence bundle",
        "./venv/bin/python -m pytest tests/ -q",
        "./venv/bin/python -m jocky evidence --iterations 1000 --out evidence",
        "# 3. tag and push",
        'git commit -am "release: v$(python -c \'import jocky; print(jocky.__version__)\')"',
        "git tag -a vX.Y.Z -m 'vX.Y.Z — <summary>'",
        "git push origin main --tags",
        "```",
        "",
        "The docs site reads its version banner from `src/lib/versions.generated.js`,",
        "which this script regenerates from `git tag` on every build.",
        "",
    ]
    target = SITE_DIR / "content" / "project" / "releases.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    version = package_version()
    releases = release_history()
    head_commit = git("rev-parse", "--short", "HEAD") or "unreleased"
    latest_tag = releases[0]["tag"] if releases else ""
    pending = commits_since(latest_tag)

    payload = [
        {
            "version": r["version"],
            "date": r["date"],
            "commit": r["commit"],
            "subject": r["subject"],
            "current": False,
        }
        for r in releases
    ]
    if not payload or payload[0]["version"] != version:
        payload.insert(
            0,
            {
                "version": version,
                "date": "unreleased",
                "commit": head_commit,
                "subject": "working tree",
                "current": True,
            },
        )
    if payload:
        payload[0]["current"] = True

    js = (
        "/* generated by site/tools/gen_versions.py — do not edit by hand */\n"
        f"export default {json.dumps(payload, indent=2)};\n"
    )
    (SITE_DIR / "src" / "lib" / "versions.generated.js").write_text(js, encoding="utf-8")
    (SITE_DIR / "static" / "versions.json").write_text(
        json.dumps({"current": version, "versions": payload}, indent=2), encoding="utf-8"
    )
    write_releases_page(releases, pending)

    print(
        f"gen_versions: current={version} tags={len(releases)} "
        f"unreleased_commits={len(pending)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
