#!/usr/bin/env python3
"""
Generate reference pages from the implementation itself.

Nothing here is hand-written: the standard library table comes from
``jocky.rt.builtins``, the detection table from ``jocky.rt.detect.CHECK_CATALOG``
and the CLI tables from ``jocky.cli.build_parser()``.  If a maintainer adds a
native or a check, the documentation changes in the same commit — the site
cannot silently describe a version of the tool that does not exist.

Outputs (all under ``site/content/``):
    language/standard-library.md
    runtime/api.md
    runtime/detection.md
    operations/cli.md
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parents[1]
REPO = SITE_DIR.parent
CONTENT = SITE_DIR / "content"

if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

GENERATED_NOTICE = (
    "<!-- generated by site/tools/gen_reference.py from the source tree — "
    "do not edit by hand -->\n"
    "<!-- regenerate with: cd site && npm run gen -->\n\n"
)


def _escape(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def core_library_page() -> str:
    from jocky.rt import builtins as rt_builtins
    from jocky.lang.vm import NativeFn

    core = rt_builtins.core_builtins()
    rows = []
    for name in sorted(core):
        fn = core[name]
        if not isinstance(fn, NativeFn):  # defensive: keep the page honest
            continue
        arity = (
            f"{fn.min_args}..{fn.max_args}" if fn.max_args is not None else f"{fn.min_args}+"
        )
        rows.append(f"| `{name}` | {arity} |")

    lines = [
        GENERATED_NOTICE,
        "# Standard library",
        "",
        "Global functions available to every script. Values are plain JOCKY data —",
        "lists are lists, maps are maps — so these compose with methods such as",
        "`list.sort()` and `str.split()`.",
        "",
        "Arity is enforced by the VM: calling with the wrong number of arguments",
        "raises a catchable error naming the function.",
        "",
        "| Function | Arity |",
        "|---|---|",
        *rows,
        "",
        "## Examples",
        "",
        "```jocky",
        "let ports = transform(net.listeners(), fn(c) { return c.local_port })",
        "emit {\"count\": count(ports), \"unique\": ports.unique().sort()}",
        "",
        "let findings = filter(det.triage().findings, fn(f) {",
        "  return f.severity == \"critical\"",
        "})",
        "for f in findings { emit {\"check\": f.check, \"title\": f.title} }",
        "",
        "print(join([\"scanned\", str(len(proc.list())), \"processes\"], \" \"))",
        "```",
        "",
        "## Higher-order helpers",
        "",
        "`transform`, `filter`, `sort_by` and `count` accept a JOCKY closure and run",
        "it inside the VM (no host round-trip), so they can call natives and other",
        "closures:",
        "",
        "```jocky",
        "let suspicious = filter(proc.list(400), fn(p) {",
        "  return contains(\"/tmp/\", p.exe) or p.memfd_exe",
        "})",
        "emit {\"suspects\": len(suspicious)}",
        "```",
        "",
    ]
    return "\n".join(lines)


def namespace_page() -> str:
    from jocky.rt import builtins as rt_builtins
    from jocky.lang.vm import NativeFn

    namespaces = rt_builtins.namespaces()
    sections = []
    overview = ["| Namespace | Functions |", "|---|---|"]
    for namespace in sorted(namespaces):
        entries = namespaces[namespace]
        overview.append(f"| [`{namespace}`](#{namespace}) | {len(entries)} |")

        rows = []
        for name in sorted(entries):
            fn = entries[name]
            if not isinstance(fn, NativeFn):
                continue
            arity = (
                f"{fn.min_args}..{fn.max_args}" if fn.max_args is not None else f"{fn.min_args}+"
            )
            rows.append(f"| `{name}` | {arity} |")
        sections += [
            f"## {namespace}",
            "",
            "| Call | Arity |",
            "|---|---|",
            *rows,
            "",
        ]

    lines = [
        GENERATED_NOTICE,
        "# Native API",
        "",
        "Natives are the only way a script touches the host. Each one is an",
        "arity-checked `NativeFn`; every read is a direct kernel-interface access",
        "(no external process is spawned, ever).",
        "",
        *overview,
        "",
        "All of these are also reachable programmatically:",
        "",
        "```python",
        "from jocky.rt.builtins import default_natives",
        "from jocky.runner import run_source",
        "",
        "result = run_source('emit {\"ok\": true}')",
        "print(result.findings, result.errors)",
        "```",
        "",
        *sections,
    ]
    return "\n".join(lines)


def detection_page() -> str:
    from jocky.rt import detect
    from jocky.rt import detect as _detect  # noqa: F401  (keeps import intent explicit)

    catalog = sorted(detect.CHECK_CATALOG, key=lambda item: item["check"])
    lines = [
        GENERATED_NOTICE,
        "# Detection checks",
        "",
        "`det.triage()` runs every check, counts findings by severity and reports how",
        "many processes and sockets it scanned, so a clean result is distinguishable",
        "from a failed run. Each check is also callable on its own.",
        "",
        "Severity scale: `info < low < medium < high < critical`.",
        "",
        "| Check | Severity | Data source |",
        "|---|---|---|",
    ]
    for entry in catalog:
        lines.append(
            f"| `{entry['check']}` | {entry['severity']} | {_escape(entry['source'])} |"
        )

    lines += ["", "## What each check means", ""]
    for entry in catalog:
        lines += [
            f"### `{entry['check']}`",
            "",
            entry["summary"],
            "",
            f"- **Source:** {entry['source']}",
            f"- **Severity:** {entry['severity']}",
            f"- **Analyst action:** {entry['action']}",
            "",
        ]

    lines += [
        "## Running a subset",
        "",
        "```jocky",
        "let report = det.triage()",
        "",
        "let critical = filter(report.findings, fn(f) { return f.severity == \"critical\" })",
        "for f in critical { emit f }",
        "",
        "emit {\"scanned\": report.scanned, \"counts\": report.counts}",
        "```",
        "",
        "## Extending the catalog",
        "",
        "A new check must be added to `jocky/rt/detect.py` **and** to",
        "`CHECK_CATALOG`; `tests/test_runtime.py` fails when a check can be emitted",
        "without a catalog entry, which keeps this page truthful.",
        "",
    ]
    return "\n".join(lines)


def cli_page() -> str:
    from jocky import cli

    parser = cli.build_parser()
    subparsers = next(
        action
        for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    )

    lines = [
        GENERATED_NOTICE,
        "# CLI reference",
        "",
        "Every command is available as `jocky <command>` (installed console script)",
        "or `python -m jocky <command>` (from a checkout).",
        "",
        "```bash",
        f"{parser.prog} --help",
        "```",
        "",
        "| Command | Purpose |",
        "|---|---|",
    ]
    for name, sub in sorted(subparsers.choices.items()):
        help_text = (sub.description or sub.prog or "").strip()
        if not help_text:
            help_text = next(
                (a.help for a in sub._actions if a.dest == "help" and a.help), ""
            )
        lines.append(f"| [`{name}`](#{name}) | {_escape(help_text or '—')} |")

    for name, sub in sorted(subparsers.choices.items()):
        lines += ["", f"## {name}", ""]
        usage = sub.format_usage().strip().replace(sub.prog or "", f"jocky {name}")
        lines += ["```text", usage, "```", ""]
        options = []
        for action in sub._actions:
            if action.dest in ("help",):
                continue
            flags = ", ".join(action.option_strings) or action.dest
            default = "" if action.default in (None, False) else f" (default: `{action.default}`)"
            options.append(
                f"| `{flags}` | {_escape(action.help or '')}{default} |"
            )
        if options:
            lines += ["| Option | Description |", "|---|---|", *options, ""]
        else:
            lines += ["_No options._", ""]

    lines += [
        "## Exit codes",
        "",
        "| Code | Meaning |",
        "|---|---|",
        "| 0 | success |",
        "| 1 | the script or artifact produced errors |",
        "| 2 | the command itself failed (bad path, unreachable server, …) |",
        "| 130 | interrupted |",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    pages = {
        CONTENT / "language" / "standard-library.md": core_library_page,
        CONTENT / "runtime" / "api.md": namespace_page,
        CONTENT / "runtime" / "detection.md": detection_page,
        CONTENT / "operations" / "cli.md": cli_page,
    }
    for path, builder in pages.items():
        content = builder()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"gen_reference: wrote {path.relative_to(REPO)} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
